
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: fabricio
  password: luvi@1904

development:
  <<: *default
  database: myblog_forum_rails_development

  
test:
  <<: *default
  database: myblog_forum_rails_test


production:
  <<: *default
  database: myblog_forum_rails_production
  username: myblog_forum_rails
  password: <%= ENV['MYBLOG_FORUM_RAILS_DATABASE_PASSWORD'] %>
